name: Monthly Web QA

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'  # 毎月1日 00:00 UTC（日本時間 朝9時）

jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CLI tools
        run: npm i -g pa11y-ci html-validate lighthouse @lhci/cli

      - name: Prepare reports folder
        run: mkdir -p reports/lighthouse

      - name: Use urls.txt
        run: |
          head -n 30 urls.txt > urls_final.txt
          echo "=== URLs to audit ==="
          nl -ba urls_final.txt

      - name: Run Pa11y (Accessibility)
        run: |
          while read -r u; do
            echo "pa11y: $u" | tee -a reports/pa11y.log
            pa11y-ci "$u" >> reports/pa11y.log 2>&1 || true
          done < urls_final.txt

      - name: Run HTML Validate
        run: |
          while read -r u; do
            echo "html-validate: $u" | tee -a reports/htmlvalidate.log
            curl -fsSL "$u" | html-validate --stdin >> reports/htmlvalidate.log 2>&1 || true
          done < urls_final.txt

      - name: Run Lighthouse
        run: |
          while read -r u; do
            echo "lighthouse: $u"
            lhci collect --url="$u" --numberOfRuns=1 --outputDir=reports/lighthouse || true
          done < urls_final.txt

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: monthly-audit-reports
          path: reports/
